[project]
name = "applemusicapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.2",
    "hypercorn>=0.17.3",
    "uvicorn>=0.31.1",
]
